services:
  kanboard:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pg_data:
      
