services:
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
