###
GET http://localhost:3000/lists/1/cards

###
GET http://localhost:3000/cards/1

###
POST http://localhost:3000/cards
Content-Type: application/json

{
  "title": "REACT COMPONENT",
  "list": 60,
  "tags": [{"id": 3}, {"id": 4}]
}

###
PUT http://localhost:3000/cards/11
Content-Type: application/json

{
 "tags": [{"id": 2}]
}

###
DELETE http://localhost:3000/cards/4

