###
GET http://localhost:3000/lists/6/cards

###
GET http://localhost:3000/cards/5

###
POST http://localhost:3000/cards
Content-Type: application/json

{
  "title": "REACT COMPONENT",
  "list": 44,
  "tags": [{"id": 2}, {"id": 4}]
}

###
PUT http://localhost:3000/cards/4
Content-Type: application/json

{
 "title": "AHOUUUUH" 
}

###
DELETE http://localhost:3000/cards/4

