###
GET http://localhost:3000/lists

###
GET http://localhost:3000/lists/60

###
POST http://localhost:3000/lists
Content-Type: application/json

{
  "name": "FTqqqq"
}

###
PUT http://localhost:3000/lists/1
Content-Type: application/json

{
  "name": "TEST2"
}

###
DELETE http://localhost:3000/lists/6




