###
GET http://localhost:3000/lists

###
GET http://localhost:3000/lists/4

###
POST http://localhost:3000/lists
Content-Type: application/json

{
  "name": "FRONT",
  "position": 6
}

###
PUT http://localhost:3000/lists/1
Content-Type: application/json

{
  "name": "TEST2"
}

###
DELETE http://localhost:3000/lists/1




