GET http://localhost:3000/tags

###
GET http://localhost:3000/tags/1

###
POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "URGENT",
  "color": "cyan"
}

###
PUT http://localhost:3000/tags/1
Content-Type: application/json

{
  "name": "TODO slow"
}

###
DELETE http://localhost:3000/tags/1

###
POST http://localhost:3000/cards/8/tags
Content-Type: application/json

{
  "cardId": 9,
  "tagIds": [3, 4]
}
