GET http://localhost:3000/lists

###
GET http://localhost:3000/lists/4

###
POST http://localhost:3000/lists
Content-Type: application/json

{
  "name": "TEEEST",
  "position": 1
}

###
PUT http://localhost:3000/lists/1
Content-Type: application/json

{

  "name": "TEST1"

}

###
DELETE http://localhost:3000/lists/1




